#server:
#  port: 8855
#spring:
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:file:./blog_app;
#
#  jpa:
#    hibernate:
#      ddl-auto: create #in prod, use update, not create
#

# MySQL Configuration
server:
  port: 8855
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blogapp
    username: akhilesh
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect